name: build

on:
  # Run on push to main
  push:
    branches:
    - main
  
  schedule:
   - cron: "0 0 * * *"
 
  # Run manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@master
       with:
         submodules: true
     - name: build
       uses: jakejarvis/hugo-build-action@master
     - name: deploy
       uses: JamesIves/github-pages-deploy-action@4.1.5
       with:
         branch: gh-pages
         folder: public
